# Generated by Django 6.1.1 on 2026-09-23 14:31

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.accounts.validators.validate_birth_date]),
        ),
    ]
