MIN_LISTING_IMAGES = 1
MAX_LISTING_IMAGES = 4

MAX_LISTING_AMENITIES = 20

MIN_PRICE_PER_NIGHT = 1
MAX_PRICE_PER_NIGHT = 10000

MIN_GUESTS = 1
MAX_GUESTS = 30

MAX_BEDROOMS = 20
MAX_BEDS = 30
MAX_BATHROOMS = 20