# Generated by Django 6.1.1 on 2026-09-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='listing_bedrooms_gte_1',
        ),
    ]
