# Generated by Django 6.1.1 on 2026-09-16 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_listing_bedrooms_gte_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='default_check_in_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='listing',
            name='default_check_out_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
