# Generated by Django 6.1.1 on 2026-09-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_default_check_in_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='default_check_in_time',
            new_name='earliest_check_in_time',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='default_check_out_time',
            new_name='latest_check_out_time',
        ),
    ]
