# Generated by Django 6.1.1 on 2026-09-20 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_default_check_in_time_listing_earliest_check_in_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewer_key', models.CharField(editable=False, max_length=80)),
                ('viewed_on', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='views', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing view',
                'verbose_name_plural': 'Listing views',
                'ordering': ('-updated_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'viewed_on'], name='listing_view_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'viewer_key', 'viewed_on'), name='unique_daily_listing_view')],
            },
        ),
    ]
