# Generated by Django 6.1.1 on 2026-09-20 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('searcher_key', models.CharField(editable=False, max_length=80)),
                ('query', models.CharField(max_length=200)),
                ('normalized_query', models.CharField(editable=False, max_length=200)),
                ('searched_on', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search history',
                'verbose_name_plural': 'Search history',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['normalized_query', '-created_at'], name='search_history_query_idx'), models.Index(fields=['user', '-created_at'], name='search_history_user_idx'), models.Index(fields=['searcher_key', '-created_at'], name='search_history_key_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('searcher_key', ''), _negated=True), name='search_history_key_not_empty'), models.CheckConstraint(condition=models.Q(('normalized_query', ''), _negated=True), name='search_history_query_not_empty')],
            },
        ),
    ]
