# Generated by Django 6.1.1 on 2026-09-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0002_remove_listing_listing_bedrooms_gte_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocked_periods', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Blocked period',
                'verbose_name_plural': 'Blocked periods',
                'ordering': ('start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='blocked_period_end_after_start')],
            },
        ),
    ]
