# Generated by Django 6.1.1 on 2026-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_blockedperiod'),
        ('listings', '0002_remove_listing_listing_bedrooms_gte_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedperiod',
            options={'ordering': ('start_at',), 'verbose_name': 'Blocked period', 'verbose_name_plural': 'Blocked periods'},
        ),
        migrations.RemoveConstraint(
            model_name='blockedperiod',
            name='blocked_period_end_after_start',
        ),
        migrations.RenameField(
            model_name='blockedperiod',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='blockedperiod',
            old_name='start_date',
            new_name='start_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='blockedperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='blocked_period_end_after_start'),
        ),
    ]
