# Generated by Django 6.1.1 on 2026-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_blockedperiod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedperiod',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blockedperiod',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
