# Generated by Django 6.1.1 on 2026-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_blockedperiod_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedperiod',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blockedperiod',
            name='reason',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('renovation', 'Renovation'), ('owner_stay', 'Owner stay'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
