MAX_REVIEW_WORDS = 350
MAX_REVIEW_CHARACTERS = 1000

MAX_REVIEW_IMAGES = 3
MAX_REVIEW_IMAGE_SIZE = 5 * 1024 * 1024  # 5 MB

ALLOWED_REVIEW_IMAGE_EXTENSIONS = (
    "jpg",
    "jpeg",
    "png",
    "webp",
)